GoogleChromeLabs/critters

README.md
react-snap have similar functionality - it extracts critical css, with the help of minimalcss and than injects it in the head and lazy load original CSS files later
=> Add react-snap to similar libraries section

README.md, src/index.js
@barak007 and I played around with this project for a bit (super cool btw!) and came across some funky behavior with keyframes (it would inline all keyframes even when not used).
We've quickly put together an addition that handles keyframes. It could probably be written in a cleaner fashion, and with more edge-cases in mind. Should probably collect all used keyframe names in a first pass, and then in a second pass only check for usage, avoiding the currently existing recursion. 
The process is based on the assumption that there is no other stylesheet consuming the same keyframes.
We've added an option (`keyframes` - `critical | all | none`) for this purpose to the configuration.
=> Add specific keyframes handling

src/index.js
If only pseudo-elements or pseudo-classes are removed, it will throw error "selector is not a valid selector".
The solution is removing child combinator in this case.
I encountered this exception at first when i ran with the https://github.com/GoogleChromeLabs/squoosh project locally.
=> Fix exception when child combinator is placed before pseudo-elements

src/index.js, test/__snapshots__/index.test.js.snap, test/index.test.js
This corrects asset/file names for reading and writing stylesheets when Webpack's `output.publicPath` setting is used.
=> Fix support for output.publicPath

src/index.js
This PR fixes the case when no inline style tags are found to merge yet critters still attempts to merge; This occurs when Critters does not generate an inline style tag or one does not exist, and the option `mergeStylesheets` is true (default). 
```
ERROR in   TypeError: Cannot read property 'textContent' of undefined
- critters.js:255 Critters.<anonymous>
[ui]/[critters-webpack-plugin]/dist/critters.js:255:23
- new Promise
- critters.js:247 Critters.mergeStylesheets
[ui]/[critters-webpack-plugin]/dist/critters.js:247:12
- critters.js:224 Critters.<anonymous>
[ui]/[critters-webpack-plugin]/dist/critters.js:224:37
```
=> Ensure an inline stylesheet exists before merging

src/index.js, test/__snapshots__/index.test.js.snap, test/fixtures/external/style.css
I noticed a simple ruleset like `:root { background: yellow }` wasn't present in the inlined CSS.
This appears to be a bug, rather than deliberate behaviour.
Merging this PR would probably address #32 as a side-effect.
=> Preserve :root ruleset

README.md, package.json, src/index.js
- Use this option to specify GLOB of other files you want to be used while evaluating critical CSS.
e.g.
``` js
if (config['inline-css']) {
prodConfig.plugins.push(new CrittersPlugin({
pruneSource: false,
logLevel: 'silent',
includeMatchingStylesheets: '*.css'
}));
}
```
// @developit
=> adding includeMatchingStylesheets option

src/index.js
Ran into this warning log while integrating Critters into a project, and noticed the following typo:
=> Fix minor typo in warning log

src/index.js, test/__snapshots__/index.test.js.snap, test/__snapshots__/standalone.test.js.snap, test/fixtures/basic/index.html
**fix: handle pseudo-class in middle of selector**
At the moment critters doesn't correctly handle pseudo-class in the middle of the selector string and pseudo-class which take a value such as `:not`
Example
```
.mat-slider:hover .mat-slider-track-background
.mat-slider-min-value:not(.mat-slider-thumb-label-showing):hover.mat-slider-disabled .mat-slider-thumb
```
More context about CSS pseudo-classes can be found https://developer.mozilla.org/en-US/docs/Web/CSS/Pseudo-classes
Closes #51
**fix: handle classes with colons**
Class names can have `:` if they are escapped. Example: `.flex\:box`
=> fix: handle pseudo-class in middle of selector

package.json, src/index.d.ts, src/index.js
With this change we improve TypeScript  type definition by adding the `logger` interface and type the `logLevel`
Exposing the logger is important so external users can implement their own logging handling.
Closes #66
=> fix: improve type definitions

packages/critters-webpack-plugin/test/__snapshots__/index.test.js.snap, packages/critters-webpack-plugin/test/fixtures/additionalStylesheets/additional.css, packages/critters-webpack-plugin/test/fixtures/additionalStylesheets/chunk.js, packages/critters-webpack-plugin/test/fixtures/additionalStylesheets/index.html, packages/critters-webpack-plugin/test/fixtures/additionalStylesheets/index.js, packages/critters-webpack-plugin/test/fixtures/additionalStylesheets/style.css, packages/critters-webpack-plugin/test/index.test.js, packages/critters/src/dom.js, packages/critters/src/index.js
Closes #69 
Simply missing a getter for `head`. 
Full stack trace of the error that this fixes. The one in the linked issue is fairly outdated and the error position is no longer correct:
```
TypeError: Cannot read property 'appendChild' of undefined
at ../../node_modules/critters-webpack-plugin/dist/critters-webpack-plugin.js:199:23
at Array.map (<anonymous>)
at ../../node_modules/critters-webpack-plugin/dist/critters-webpack-plugin.js:195:24
at Array.forEach (<anonymous>)
at CrittersWebpackPlugin.embedAdditionalStylesheet (../../node_modules/critters-webpack-plugin/dist/critters-webpack-plugin.js:188:48)
at CrittersWebpackPlugin.process (../../node_modules/critters/dist/critters.js:633:12)
at handleHtmlPluginData (../../node_modules/critters-webpack-plugin/dist/critters-webpack-plugin.js …
```
=> fix: Adding in missing getter for `document.head`

packages/critters-webpack-plugin/package.json
**What's the problem this PR addresses?**
`critters-webpack-plugin` tries to require `html-webpack-plugin` (https://github.com/GoogleChromeLabs/critters/blob/5e32531caf7540842ff9af99e9449975bf0ad399/packages/critters-webpack-plugin/src/index.js#L71-L75) but doesn't declare it as a dependency which means under strict dependency environments or if hoisting isn't in its favour it wont get access to it.
https://yarnpkg.com/advanced/rulebook/#packages-should-only-ever-require-what-they-formally-list-in-their-dependencies
Ref https://github.com/preactjs/preact-cli/pull/1608#issuecomment-988417698 (cc @rschristian)
**How did you fix it?**
Based on how `critters-webpack-plugin` is trying to use `html-webpack-plugin` I added it as an optional peer dependency.
=> fix: add missing peer dependency `html-webpack-plugin`

packages/critters/src/css.js
Applies the suggested fix in #86. Should fix a lot of packages that are dependent on tailwind or windicss animations (like the Vitesse starter template https://github.com/antfu/vitesse, https://github.com/antfu/vite-ssg/issues/158).
=> fix: scss code using keyframes should successfully transform

packages/critters/src/index.js
This should fix #94 in both CJS and ESM bundles.
=> Fix fs import

packages/critters-webpack-plugin/src/index.js
=> fix: add createRequire for try/catched require('html-webpack-plugin').getHooks(compilation)

packages/critters/src/index.js, packages/critters/test/__snapshots__/critters.test.js.snap, packages/critters/test/src/index.html, packages/critters/test/src/styles.css
Prior to this change sub-selectors where incorrectly processed.
Example `div:is(:hover, .active)` would be turned into `div:is(, .active)` which caused the parser to emit an `Empty sub-selector` error.
//cc @janicklas-ralph
=> fix: handle sub-selector with both classes and pseudo selectors

packages/critters/src/dom.js, packages/critters/test/critters.test.js
The latest version of critters introduced a breaking behaviour which causes special characters to be encoded.
This commit removes this behaviour and restores the previous one.
See: https://github.com/angular/angular-cli/issues/25388
=> fix: do not encode special characters

packages/critters/src/dom.js, packages/critters/test/critters.test.js
Decoding the entities within HTML content can lead to undoing escapes
=> fix: prevent document parsing from decoding entities within HTML document

packages/critters/src/css.js
`postcss-media-query-parser` is a CommonJS (CJS) module, and its default export differs from the ECMAScript Module (ESM) format. This variance causes `critters` to encounter issues when bundled with webpack.
=> fix: bundling with Angular CLI and Webpack

packages/critters/src/index.js, packages/critters/test/src/styles.css
The Angular CLI would like to support `critters` in legal comments. Legal comments have a leading `!` and aren't removed at build times. 
Cf https://esbuild.github.io/api/#legal-comments
cc @alan-agius4
=> fix: support legal comments

packages/critters-webpack-plugin/test/__snapshots__/index.test.js.snap, packages/critters/src/index.js, packages/critters/test/__snapshots__/critters.test.js.snap, packages/critters/test/critters.test.js
Before this commit, the generated link tags were missing some attributes, which caused issues when attributes like `integrity`, `nonce`, and `crossorigin` were not applied.
See https://github.com/angular/angular-cli/issues/27881 for more context.
=> fix: retain all attributes from the original link tag
